version: '3.1'

services:
    db:
        build: 
            context: ./db
        restart: always
        ports: 
            - "5432:5432"
        volumes: 
            - "./db/.dbdata:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: codeworkers 

    spiders:
        build: 
            context: ./crawler
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: codeworkers 
        depends_on:
            - db 

    app:
        build: 
            context: ./api
        restart: always
        ports: 
            - "3000:3000"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: codeworkers 
        depends_on:
            - db 
