version: '3.1'

services:
    db:
        image: base-scrapy
        ports: 
            - "2345:5432"
        volumes: 
            - "./db/.dbdata:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: codeworkers 

    app:
        image: spider
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: codeworkers 
        depends_on:
            - db 
